name: workflow.yml
on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: master

      - name: Setup JDK 17
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR with Maven
        run: mvn clean package

      - name: Copy WAR to remote Tomcat
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "target/weather-viewer.war"
          target: "/opt/apache-tomcat-10.1.39/webapps"

      - name: Restart Tomcat service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: >
                  mv /opt/apache-tomcat-10.1.39/webapps/target/weather-viewer.war /opt/apache-tomcat-10.1.39/webapps;
                  rm -r /opt/apache-tomcat-10.1.39/webapps/target;
                  /opt/apache-tomcat-10.1.39/bin/shutdown.sh;
                  /opt/apache-tomcat-10.1.39/bin/startup.sh